### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by oxygen16** [lgeiger/ide-python#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 0.1.1

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\wanch\.atom\packages\ide-python\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (native)
    at MessageBuffer.tryReadHeaders (/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:185:43)
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -5:06.7.0 application:new-file (input.hidden-input)
     -5:03.7.0 application:open-file (input.hidden-input)
     -4:35.2.0 application:open-folder (input.hidden-input)
     -2:18.8.0 grammar-selector:show (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -2:16.2.0 editor:consolidate-selections (input.hidden-input)
     -2:16.2.0 core:cancel (input.hidden-input)
     -2:14.2.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -2:12.5.0 editor:consolidate-selections (input.hidden-input)
     -2:12.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.2 
file-type-icons 1.3.4 
ide-java 0.6.0 
ide-python 0.1.1 
ide-typescript 0.6.1 
```

**Comment by lgeiger** [comment]
Please provide steps to reproduce this issue. Feel free to reopen if you still have problems.
