### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by estevez121** [lgeiger/ide-python#142]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.0.0

### Stack Trace

Failed to activate the ide-python package

```
At Cannot find module 'vscode-languageserver-types'

Error: Cannot find module 'vscode-languageserver-types'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/ide-python/node_modules/vscode-languageserver-protocol/lib/main.js:37:10)
    at /packages/ide-python/node_modules/vscode-languageserver-protocol/lib/main.js:75:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:17:10)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:400:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/convert.js:3:12)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/convert.js:204:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-runner 2.7.1 
goto-definition 1.3.4 
ide-python 1.0.0 
platformio-ide-terminal 2.8.4 
remote-sync 4.1.8 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
```

**Comment by lgeiger** [comment]
Please try reinstalling `ide-python`

**Comment by lenny-r** [comment]
atom- 1.45.0
osx- 10.15.4 (19E266)


Error: Package not initialized
    at Object.moduleExports.(anonymous function) [as addProvider] (/Users/admin/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:61:15)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122126)
    at ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3216751)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3225037)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3222013)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382742)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382704)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:942215
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:936821)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125033)
    at ChildProcess.o.process.on.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125239)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
