### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by bwolfordpp** [lgeiger/ide-python#165]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.4.1

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/bw/.atom/packages/ide-python/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-python/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-python/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-python/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-puppet/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-puppet/node_modules/atom-languageclient/build/lib/languageclient.js:131:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-puppet/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:181:22)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173795)
    at disposables.add.displayLayer.onDidChange.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:6510)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173795)
    at DisplayLayer.emitDeferredChangeEvents (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:91874)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504278)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492297)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:95794)
```

### Commands

```
     -4:14.9.0 core:copy (input.hidden-input)
     -4:10.9.0 editor:newline (input.hidden-input)
     -4:09.9.0 core:paste (input.hidden-input)
     -4:08.1.0 core:save (input.hidden-input)
     -3:25.6.0 editor:newline (input.hidden-input)
 14x -3:17.5.0 core:select-up (input.hidden-input)
  2x -3:15 core:select-left (input.hidden-input)
     -3:13.8.0 core:copy (input.hidden-input)
     -3:10.5.0 core:paste (input.hidden-input)
     -3:06.3.0 editor:newline (input.hidden-input)
     -3:04.5.0 core:backspace (input.hidden-input)
     -2:57.3.0 core:save (input.hidden-input)
 16x -2:33 core:backspace (input.hidden-input)
     -2:19.8.0 core:save (input.hidden-input)
 55x -0:12.6.0 core:backspace (input.hidden-input)
     -0:04.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
git-blame 1.8.0 
hiera-eyaml 0.6.1 
ide-puppet 1.3.1 
ide-python 1.4.1 
intentions 1.1.5 
language-ansible 0.2.2 
language-puppet 0.23.0 
linter 2.3.0 
linter-puppet-lint 0.8.4 
linter-shellcheck 1.6.0 
linter-ui-default 1.7.1 
sort-lines 0.19.0 
split-diff 1.6.0 
teletype 0.13.3 
```

**Comment by wirstrom** [comment]
I get the same error, even after disabling ide-python. Why was this issue closed?

**Comment by mgomersbach** [comment]
Yeah can be re-opened as it happens here as well.

**Comment by mgomersbach** [comment]
Also happens in last update
