### ISSUE TITLE
ide-python does not work on out of project files

### ISSUE THREAD

**Issue by Th3R4nd0m** [lgeiger/ide-python#168]
What the titles says. If I open a python file, and it is not included in any project, python-ide won't do nothing for it.

**Comment by Th3R4nd0m** [comment]
actually, it doesn't even work for files in my project :) 
pls help

**Comment by Th3R4nd0m** [comment]
![Screenshot from 2019-09-10 19-07-01](https://user-images.githubusercontent.com/43180911/64630665-3ff9cc00-d3fe-11e9-965a-d534b46c51cd.png)

**Comment by Th3R4nd0m** [comment]
python3 -m pyls --help
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/pyls/__main__.py", line 7, in <module>
    from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
  File "/usr/local/lib/python3.7/dist-packages/pyls/python_ls.py", line 10, in <module>
    from . import lsp, _utils, uris
  File "/usr/local/lib/python3.7/dist-packages/pyls/uris.py", line 8, in <module>
    from pyls import IS_WIN
ImportError: cannot import name 'IS_WIN' from 'pyls' (/usr/local/lib/python3.7/dist-packages/pyls/__init__.py)

**Comment by Th3R4nd0m** [comment]
solved. uninstalled language-server and installed again, enforced python3, and 

> apm enable language-python.
