### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by KaniRobinson** [lgeiger/ide-python#3]
**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 0.1.0

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/KaniRobinson/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:604

Error: Connection is closed.
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:233:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:126:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:196:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:823:24)
    at decorationLayerDisposable.textDecorationLayer.onDidInvalidateRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:161:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:241:28)
    at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:206:32
    at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -3:26.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:25.2.0 editor:consolidate-selections (input.hidden-input)
     -3:25.2.0 core:cancel (input.hidden-input)
     -3:24.3.0 command-palette:toggle (input.hidden-input)
  2x -3:21.5.0 core:move-down (input.hidden-input)
     -3:20.1.0 core:confirm (input.hidden-input)
     -3:20.1.0 settings-view:install-packages-and-themes (input.hidden-input)
     -3:12.4.0 core:confirm (input.hidden-input)
     -2:15.2.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:12.5.0 editor:newline (input.hidden-input)
     -1:48.5.0 core:save (input.hidden-input)
     -1:09.9.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.9.0 editor:consolidate-selections (input.hidden-input)
     -1:08.9.0 core:cancel (input.hidden-input)
     -0:55.8.0 core:save (input.hidden-input)
     -0:35.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
ide-python 0.1.0 
ide-typescript 0.1.6 
language-vue 0.23.1 
react-snippets 0.7.2 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by lgeiger** [comment]
Could you provide more information on how to reproduce this error?

**Comment by lgeiger** [comment]
Looks like this error also happens in other IDE packages: https://github.com/atom/ide-typescript/issues/17

**Comment by tomer** [comment]
```bash
killall pyls 
```
…Then switch back to Atom and continue editing your Python code. 😄 

```
**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: "Fedora release
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 0.1.1


### Stack Trace

Uncaught Error: Connection is closed.

```
At /home/tomer/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:604

Error: Connection is closed.
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:124:10)
    at TextEditorSyncAdapter.sendIncrementalChanges (/packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:202:24)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1563:28)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:922:20)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1673:32)
    at /usr/share/atom/resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1651:28)
```

### Commands

```
     -4:22.9.0 core:save (input.hidden-input)
     -4:16.2.0 editor:newline (input.hidden-input)
     -4:15.3.0 intentions:highlight (input.hidden-input)
     -4:15.1.0 core:save (input.hidden-input)
     -4:13.6.0 core:move-up (input.hidden-input)
     -4:13.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -4:12.1.0 core:move-down (input.hidden-input)
     -4:11.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -4:10.6.0 core:move-left (input.hidden-input)
  2x -4:08.9.0 core:delete (input.hidden-input)
  8x -3:59.3.0 core:backspace (input.hidden-input)
     -3:54.9.0 intentions:highlight (input.hidden-input)
     -3:54.7.0 core:save (input.hidden-input)
  5x -3:16.5.0 core:backspace (input.hidden-input)
     -3:13.5.0 intentions:highlight (input.hidden-input)
     -3:13.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-ide-ui 0.3.3 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
file-icons 2.1.12 
Hydrogen 1.22.0 
ide-json 0.1.0 
ide-python 0.1.1 
intentions 1.1.5 
linter 2.2.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.10 
output-panel 0.3.4 
platformio-ide-terminal 2.6.0 
```

**Comment by exploide** [comment]
Can reproduce this without killing pyls explicitly. Simple switching to the settings tab and toggling pydocstyle triggers this issue.

Since this is labeled an upstream issue, is there already an opened issue somewhere?

**Comment by alexandernst** [comment]
This can be reproduced by killing the Python process that feeds data to Atom.

**Comment by lgeiger** [comment]
> Can reproduce this without killing pyls explicitly. Simply switching to the settings tab and toggling a plugin like pydocstyle triggers this issue.

I can't reproduce this. @exploide Which operating system are you on?

> Since this is labeled an upstream issue, is there already an opened issue somewhere?

See https://github.com/lgeiger/ide-python/issues/3#issuecomment-329191377

**Comment by exploide** [comment]
I'm on Fedora 26. But I can't reproduce any longer. The first time I tested this, it was completely reproducible, even after restarting atom. Now the issue is gone for me. (At least it seems to be. I'm not using it heavily at the moment.)

But it might persist when killing the processes, as other people mentioned.

**Comment by j-f1** [comment]
I’ve managed to find out that this is caused by this error in the child process:

```
Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:804:14)
```

Not very helpful, unfortunately.
