### ISSUE TITLE
Uncaught (in promise) Error: Server Error

### ISSUE THREAD

**Issue by autonomy-dcuddihy** [lgeiger/ide-python#50]
I'm having an issue where ide-python works fine for a while, then stops providing Python IDE functionality: 

* Linter results stop updating;
* Hyperclick just spins when I ctrl-hover over a symbol;
* Outline view just shows a spinner;
* CTRL-SHIFT-I - Console shows a bunch of Server Error messages like:

```
/home/ubuntu/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/messages.js:46 Uncaught (in promise) Error: Server error
    at new ResponseError (/home/ubuntu/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/home/ubuntu/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/home/ubuntu/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at Immediate.<anonymous> (/home/ubuntu/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

My environment looks like:

* Ubuntu 14.04 running on VirtualBox;
* Atom 1.22.1 x64
* atom-ide- 0.6.0
* ide-python 0.3.0
* python 3.6.0 :: Continuum Analytics, Inc.
* `pyls.__version__` == 0.11.1

Let me know if there are any other details about my environment or issue that may be helpful.

My work-around is to restart Atom:  I regain normal ide-python functionality until the next failure.  I have not discerned any clear pattern as to what triggers it.

Any help greatly appreciated. Thanks!
-Dave

**Comment by AlecZorab** [comment]
Getting the same issue in macos sierra with the same versions of everything above, with the exception of python, which is python 3.6.2.

**Comment by Larandar** [comment]
Seem a generalization of #44

**Comment by kbatbouta** [comment]
On Sierra I got it working using ```pyls=0.8.0``` and ```Jedi=0.10.2``` 
because ```pyls=0.11.1``` changed inner working by using Jedi and Rope together and adding parallelism to autocomplete and also they changed a lot of other things which is why

>  @lgeiger  should add pyls=0.8.0 and Jedi=0.10.2 as recommended versions to ensure best  compatibility
