### ISSUE TITLE
Failed to load the ide-python package

### ISSUE THREAD

**Issue by i-mighty** [lgeiger/ide-python#55]
[Enter steps to reproduce below:]

1. ..Search for package "python run".
2.  Select "ide-python" to install...

**Atom Version**: 0.188.0-d462895
**System**: linux 4.9.0-kali3-686-pae
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package, v0.3.0

### Stack Trace

Failed to load the ide-python package

```
At /root/.atom/packages/ide-python/lib/main.js:2
const { shell } = require("electron");
      ^
Unexpected token {

/root/.atom/packages/ide-python/lib/main.js:2
const { shell } = require("electron");
      ^
SyntaxError: Unexpected token {
  at exports.runInThisContext (vm.js:75:16)
  at Module._compile (module.js:458:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:678:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:460:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  4x -7:24.2 window:increase-font-size (atom-pane.pane.active)
     -7:21.4 window:decrease-font-size (atom-pane.pane.active)
  3x -7:19.9 window:increase-font-size (atom-pane.pane.active)
     -5:44.4 core:confirm (atom-text-editor.editor.mini)
 26x -3:25.4 core:backspace (atom-text-editor.editor.mini)
     -3:15.8 core:confirm (atom-text-editor.editor.mini)
     -1:14.9 window:toggle-dev-tools (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-clock, v0.1.15
ide-python, v0.3.0

# Dev
No dev packages
```

**Comment by lgeiger** [comment]
You are using a very old version of Atom. ide-python needs Atom 1.21 or later. Please upgrade and try again.

**Comment by lgeiger** [comment]
Feel free to reopen if the above suggestion doesn't fix your issue.
