### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by alexanderepstein** [lgeiger/ide-python#8]
[Enter steps to reproduce:]

1. Have ide-python installed
2. Open a java file 
3. Close it

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: elementary OS
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 0.1.1

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /home/fsociety/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:191

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:191:27)
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -5:16.9.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.seti-compact.hide-project-tab.seti-icons.seti-animate.theme-one-dark-syntax.theme-seti-ui)
     -5:10.8.0 core:backspace (input.hidden-input)
  2x -5:03.9.0 core:copy (div#linter-panel.)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.3.1 
autocomplete-clang 0.11.3 
autocomplete-java 1.2.7 
autocomplete-python 1.10.2 
busy-signal 1.4.3 
highlight-selected 0.13.1 
ide-java 0.6.0 
ide-python 0.1.1 
intentions 1.1.5 
language-cpp14 0.6.2 
linter 2.2.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-ruby 1.2.6 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
seti-ui 1.9.0 
sourcerer 2.0.0 
```

**Comment by lgeiger** [comment]
This error may come from the `ide-java` package: https://github.com/atom/ide-java/issues/8

**Comment by lgeiger** [comment]
This error was fixed in the latest `ide-java` release: https://github.com/atom/ide-java/issues/8

**Comment by maxim-lian** [comment]
Hi @lgeiger - I didn't know you were on this package too - great work across the board.

I get this error, though don't have `ide-java` installed - let me know you have any ideas?


**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 0.5.0


### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/maximilian/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
 17x -0:20.6.0 core:move-down (input.hidden-input)
     -0:17.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:16.7.0 datatip:toggle (input.hidden-input)
     -0:15.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:15.4.0 datatip:toggle (input.hidden-input)
     -0:15.1.0 core:cut (input.hidden-input)
  2x -0:14.9.0 core:move-up (input.hidden-input)
     -0:14.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:13.4.0 core:paste (input.hidden-input)
     -0:09.3.0 datatip:toggle (input.hidden-input)
  3x -0:09.1.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:08.3.0 datatip:toggle (input.hidden-input)
  2x -0:07.5.0 core:move-down (input.hidden-input)
     -0:06.9.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:06.6.0 core:backspace (input.hidden-input)
     -0:06.1.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.7.1 
atom-python-test 0.9.0 
autocomplete-python 1.10.5 
block-travel 1.0.5 
build 0.70.0 
build-cargo 2.0.0 
busy 0.7.0 
busy-signal 1.4.3 
docker 0.8.0 
file-icons 2.1.15 
highlight-selected 0.13.1 
Hydrogen 2.2.2 
ide-python 0.5.0 
incremental-search 5.2.2 
intentions 1.1.5 
language-docker 1.1.8 
language-ini 1.19.0 
language-rust 0.4.12 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-flake8 2.3.0 
linter-less 2.6.0 
linter-ui-default 1.6.10 
project-manager 3.3.5 
python-debugger 0.2.0 
python-indent 1.1.4 
python-tools 0.6.9 
remote-sync 4.1.8 
sort-lines 0.18.0 
sourcegraph 1.0.5 
sync-settings 0.8.3 
teletype 0.6.0 
wakatime 7.0.4 
```

**Comment by lgeiger** [comment]
Thanks Maximilian.

Could you provide some steps to reproduce this?

Also deactivating other Python related packages like autocomplete-plus, python-tools, ... May help in general when using ide-python.

**Comment by maxim-lian** [comment]
Nothing dependable on repro. For posterity, this occurred on `from a import b.c.` (on that final period). I'll report back if I can get something reproducible
